-- POSTGRESQL doesn't create indexes on constraints
CREATE INDEX OPERATION_ACCOUNT ON OPERATION (ACCOUNT);
CREATE INDEX OPERATION_CARD ON OPERATION (CARD);
CREATE INDEX OPERATION_TYPE ON OPERATION (TYPE);
CREATE INDEX CARD_ACCOUNT ON CARD (ACCOUNT);
CREATE INDEX USR_ACCOUNT_ACCOUNT ON USR_ACCOUNT (ACCOUNT_ID);
CREATE INDEX USR_ACCOUNT_USER ON USR_ACCOUNT (USR_ID);
CREATE INDEX USR_LOGIN ON USR (LOGIN);
CREATE INDEX ACCOUNT_NUMBER on ACCOUNT (NUMBER);
